# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "tf-bucket-ffp"
    encrypt = true
    key     = "prod/ec2/terraform.tfstate"
    region  = "eu-west-1"
  }
}
