name: Terragrunt Apply All (deploy)
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
    steps:
    - uses: actions/checkout@v1
    - name: Install Terraform and Terragrunt
      run: |
        brew install terragrunt 
    - name: Get Versions
      run: |
        terragrunt --version
        terraform --version
    - name: Setup infra modules deploy key
      run: |
        mkdir ~/.ssh
        echo "${{ secrets.INFRA_MODULES_DEPLOY_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa github.com
    - name: Terragrunt plan-all
      run: terragrunt plan-all

    - name: Terragrunt apply-all
      run: terragrunt apply-all --terragrunt-non-interactive
