# This is a basic workflow to help you get started with Actions

name: Validate Terraform Code

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the main branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: eu-west-1

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: install terraform and terragrunt
        run: |
          brew tap hashicorp/tap
          brew install hashicorp/tap/terraform
          brew install terragrunt

      - name: Get Versions
        run: |
          terragrunt --version
          terraform --version

      # Runs a single command using the runners shell
      #- name: Terraform Init
      #  run: find . -type f -name "*.tf" -exec dirname {} \;|sort -u | while read m; do (cd "$m" && terraform init -input=false -backend=false) || exit 1; done

      - name: Terragrunt plan-all
        run: terragrunt plan-all
